name: Package Validation

on:
  push:
    branches: [main, release/**]
  pull_request:
    branches: [main, release/**]

jobs:
  validate-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
          run_install: false

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Run publint
        run: npx publint

      - name: Run arethetypeswrong
        run: npx @arethetypeswrong/cli . --pack
